apiVersion: apps/v1
kind: Deployment
metadata:
  name: auth-service
  namespace: kube-sg
spec:
  replicas: 1
  selector:
    matchLabels: { app: auth-service }
  template:
    metadata:
      labels: { app: auth-service }
    spec:
      containers:
      - name: auth-service
        image: shreenidhidev/auth-service:v1
        imagePullPolicy: Always
        ports:
        - containerPort: 8080
        env:
        # Pass database connection info as separate variables
        - name: POSTGRES_HOST
          value: "postgres-rw.kube-sg.svc.cluster.local"
        - name: POSTGRES_DB
          value: "dbname"
        # Fetch credentials securely from the secret
        - name: POSTGRES_USER
          valueFrom:
            secretKeyRef:
              name: postgres-app
              key: username
        - name: POSTGRES_PASSWORD
          valueFrom:
            secretKeyRef:
              name: postgres-app
              key: password
        resources:
          requests:
            memory: "64Mi"
            cpu: "250m"
          limits:
            memory: "128Mi"
            cpu: "500m"