apiVersion: argoproj.io/v1alpha1
kind: Application

metadata:
  name: app
  namespace: argocd

spec:
  project: default
  source:
    repoURL: "https://github.com/ICodeBTW/Project-B-GitOps.git"
    targetRevision: HEAD
    path: "Kubernetes/app/"
  destination:
    server: "https://kubernetes.default.svc"
    namespace: default
  syncPolicy:
    automated:
      prune: true
      selfHeal: true
    syncOptions:
      - CreateNamespace=true
